### ISSUE TITLE
Ponder support?

### ISSUE THREAD

**Issue by CMCanavessi** [mhouppin/stash-bot#1]
Hi, are you planning on adding ponder? In my tournaments, I use 1m + 1s and 2m + 1s, 1 thread and ponder ON and Stash is at quite a disadvantage without pondering.

**Comment by mhouppin** [comment]
That's a feature I still have to think about. Shouldn't be too hard to implement, I just need to set up time usage correctly for it, and make some tests. Shouldn't take more than a week. (Sorry for the late reply btw)

**Comment by CMCanavessi** [comment]
That's great to know! According to Andrew Grant, implementing ponder was "just a couple lines of code" :D

**Comment by mhouppin** [comment]
After some investigation, adding ponder conflicts with the current threading system I use, so I still need to find a way to add it without breaking other stuff (like exiting search when receiving "stop" commands). It might require a partial rewrite of the engine communication. Hopefully I can keep the changes under 50 lines ^^

**Comment by mhouppin** [comment]
https://github.com/mhouppin/stash-bot/tree/add_ponder_support

Untested for now, I'll run a head-to-head match against development version to ensure everything works as expected.
