### ISSUE TITLE
stash-bot Elo Rating ? 

### ISSUE THREAD

**Issue by chess-com** [mhouppin/stash-bot#103]
Hi! I Searched stash-bot in CCRL BLITZ RATING, but I couldn't find it, What's the Elo rating for stash-bot?

https://ccrl.chessdom.com/ccrl/

**Comment by mhouppin** [comment]
https://ccrl.chessdom.com/ccrl/404/cgi/engine_details.cgi?print=Details&each_game=0&eng=Stash%2034.0%2064-bit#Stash_34_0_64-bit
Not an issue, closing this.

**Comment by chess-com** [comment]
Thanks 💕, And how can I see the stash games?

**Comment by mhouppin** [comment]
http://ccrl.chessdom.com/ccrl/404/games-by-engine/Stash_34_0_64-bit.bare.[1013].pgn.7z
Again, this is not an issue.
