### ISSUE TITLE
Possible incorrect code in "evaluate_safety()"

### ISSUE THREAD

**Issue by JoAnnP38** [mhouppin/stash-bot#173]
In function evaluate_safety() you have the following expression defining "weak squares":

        // We define weak squares as squares that we attack where the enemy has
        // no defenders, or only the King as a defender.
        bitboard_t weak = eval->attacked[us] & ~eval->attackedTwice[them]
                          & (~eval->attacked[them] | eval->attackedBy[them][KING]);

Shouldn't the second _and_ actually be an _or_? Or

        // We define weak squares as squares that we attack where the enemy has
        // no defenders, or only the King as a defender.
        bitboard_t weak = eval->attacked[us] & ~eval->attackedTwice[them]
                          | (~eval->attacked[them] | eval->attackedBy[them][KING]);

**Comment by mhouppin** [comment]
Well, we want weak squares to be the squares we are attacking, and where there's no defenders, or only the bare King.
We can break that down to 3 conditions:
- we are attacking them (`eval->attacked[us]`)
- **and** they are not defended twice (`& ~eval->attackedTwice[them]`)
- **and** they are not defended at all, or the King defends them (`& (~eval->attacked[them] | eval->attackedBy[them][KING])`).

Changing the second `&` to an `|` includes back the squares defended twice if the King is one of the defenders, which we don't want to.
